imports:
    - name: tensorflow-cluster
      path: tensorflow-cluster.jinja
    - name: jupyter-service
      path: jupyter-service.jinja
resources:
  - type: tensorflow-cluster
    properties:
        image: gcr.io/oscon-tf-workshop/tf-worker
        namespace: tensorflow
        jobs:
            - name: ps
              num_tasks: 2
            - name: workers
              num_tasks: 3
  - type: jupyter-service
    properties:
        namespace: tensorflow
        password: 'a good password'
