kind: PersistentVolume
apiVersion: v1
metadata:
  name: pd1
  namespace: default
spec:
    capacity:
        storage: 20Gi
    hostPath:
        path: pd1
    accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
    persistentVolumeReclaimPolicy: Recycle
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pd2
  namespace: default
spec:
    capacity:
        storage: 20Gi
    hostPath:
        path: pd2
    accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
    persistentVolumeReclaimPolicy: Recycle
---
# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
kind: ConfigMap
apiVersion: v1
metadata:
    name: tensorflow-cluster-config
    namespace: default
data:
    clusterconfig: >
        {
            "ps": [
                "ps-0.default.svc.cluster.local:8080",
                "ps-1.default.svc.cluster.local:8080",
                "ps-2.default.svc.cluster.local:8080",
                "ps-3.default.svc.cluster.local:8080",
            ],
            "worker": [
                "worker-0.default.svc.cluster.local:8080",
                "worker-1.default.svc.cluster.local:8080",
                "worker-2.default.svc.cluster.local:8080",
                "worker-3.default.svc.cluster.local:8080",
                "worker-4.default.svc.cluster.local:8080",
                "worker-5.default.svc.cluster.local:8080",
                "worker-6.default.svc.cluster.local:8080",
                "worker-7.default.svc.cluster.local:8080",
            ],
            "master": [
                "master-0.default.svc.cluster.local:8080",
            ],
        }
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorflow-logs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notebooks
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Service
apiVersion: v1
metadata:
  name: ps-0
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: ps
    task: '0'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ps-0
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: ps
      task: '0'
  template:
    metadata:
      labels:
        job: ps
        task: '0'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: ps-1
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: ps
    task: '1'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ps-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: ps
      task: '1'
  template:
    metadata:
      labels:
        job: ps
        task: '1'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: ps-2
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: ps
    task: '2'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ps-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: ps
      task: '2'
  template:
    metadata:
      labels:
        job: ps
        task: '2'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: ps-3
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: ps
    task: '3'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ps-3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: ps
      task: '3'
  template:
    metadata:
      labels:
        job: ps
        task: '3'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: worker-0
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: worker
    task: '0'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-0
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: worker
      task: '0'
  template:
    metadata:
      labels:
        job: worker
        task: '0'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: worker-1
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: worker
    task: '1'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: worker
      task: '1'
  template:
    metadata:
      labels:
        job: worker
        task: '1'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: worker-2
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: worker
    task: '2'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: worker
      task: '2'
  template:
    metadata:
      labels:
        job: worker
        task: '2'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: worker-3
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: worker
    task: '3'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: worker
      task: '3'
  template:
    metadata:
      labels:
        job: worker
        task: '3'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: worker-4
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: worker
    task: '4'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-4
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: worker
      task: '4'
  template:
    metadata:
      labels:
        job: worker
        task: '4'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: worker-5
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: worker
    task: '5'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-5
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: worker
      task: '5'
  template:
    metadata:
      labels:
        job: worker
        task: '5'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: worker-6
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: worker
    task: '6'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-6
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: worker
      task: '6'
  template:
    metadata:
      labels:
        job: worker
        task: '6'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: worker-7
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: worker
    task: '7'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker-7
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: worker
      task: '7'
  template:
    metadata:
      labels:
        job: worker
        task: '7'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
---
kind: Service
apiVersion: v1
metadata:
  name: master-0
  namespace: default
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    job: master
    task: '0'
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: master-0
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: master
      task: '0'
  template:
    metadata:
      labels:
        job: master
        task: '0'
    spec:
      containers:
        - name: tf-grpc-server
          image: gcr.io/google-samples/tf-k8s-worker
          ports:
            - name: grpc-server
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: CLUSTER_CONFIG
              valueFrom:
                  configMapKeyRef:
                      name: tensorflow-cluster-config
                      key: clusterconfig
          resources:
            requests:
              cpu: 1
        - name: jupyter-server
          image: gcr.io/google-samples/tf-jupyter-server
          args:
            - "--notebook-dir=u'/notebooks'"
            - "--port=80"
          ports:
            - name: jupyter
              containerPort: 80
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jupyter
                  key: password
            - name: CLUSTER_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: tensorflow-cluster-config
                  key: clusterconfig
          volumeMounts:
            - name: tensorflow-logs
              mountPath: /var/log/tensorflow
            - name: notebooks
              mountPath: /notebooks
        - name: tensorboard-server
          image: gcr.io/tensorflow/tensorflow:latest-devel
          ports:
            - name: tensorboard
              containerPort: 6006
          command:
            - /tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard
            - --logdir=/var/log/tensorflow
          volumeMounts:
            - name: tensorflow-logs
              mountPath: /var/log/tensorflow
              readOnly: true
      volumes:
        - name: tensorflow-logs
          persistentVolumeClaim:
            claimName: tensorflow-logs
        - name: notebooks
          persistentVolumeClaim:
            claimName: notebooks
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-external
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: jupyter
      port: 80
    - name: tensorboard
      port: 6006
  selector:
    job: master
    task: '0'
---
